### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by kareem9090** [devanshbatham/OpenRedireX#16]
Traceback (most recent call last):
File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 126, in
main()
File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 108, in main
asyncio.run(redirme(args.list, args.payloads, args.keyword))
File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 80, in redirme
await gen_tasks(session, url_list, payload_list, keyword)
File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 39, in gen_tasks
results = await asyncio.gather(*tasks)
File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 46, in getResponse
async with session.get(r_url, allow_redirects=True, timeout=10) as response:
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in aenter
self._resp = await self._coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 492, in _request
req = self._request_class(
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in init
self.update_host(url)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 88407996/articles?portalId=5212498&currentArticleId=10127762043&currentArticleLanguage=en&currentUrl=https://help.aware360.com/knowledge-base/setting-your&ssoLogin=false

**Comment by rakshitks** [comment]
Try this once
Please follow these steps to resolve the error

1. Install python3.7
`sudo apt install python3.7-minimal`

2. Install python3.7 dev
`sudo apt-get install python3.7-dev`

**Comment by devanshbatham** [comment]
Closing this issue as I have updated the entire script. File a new issue if you face any problems running it
