### ISSUE TITLE
giving error asyncio unable to run the tool

### ISSUE THREAD

**Issue by balook** [devanshbatham/OpenRedireX#4]
Traceback (most recent call last):
  File "./openredirex.py", line 126, in <module>
    main()
  File "./openredirex.py", line 108, in main
    asyncio.run(redirme(args.list, args.payloads, args.keyword))
AttributeError: module 'asyncio' has no attribute 'run'

Im getting this while running

**Comment by kherwata** [comment]
### solved by  : 
1 - going to : https://www.python.org/downloads/
2 - downloading python3.8.2
3 - installing it using the following commands: 
``` ./configure ```
``` make ```
``` make test ```
``` sudo make install ```
4 - then runing  : 
``` sudo pip3 install aiohttp ```
##### and finally it worked : 
``` python3 openredirex.py -l urls.txt -p payloads.txt --keyword FUZZ ```

@devanshbatham thanks for those awesome tools

**Comment by devanshbatham** [comment]
Thanks mate for the feedback, credit goes to  @NullPxl 😊

**Comment by NullPxl** [comment]
@balook `asyncio.run()` is a [new function in python 3.7](https://docs.python.org/3/library/asyncio-task.html#asyncio.run).  Try running it with python3.7+ with aiohttp installed.  Try following kherwata's guide on installation if you get stuck.

**Comment by kareem9090** [comment]
Traceback (most recent call last):
  File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 126, in <module>
    main()
  File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 108, in main
    asyncio.run(redirme(args.list, args.payloads, args.keyword))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 80, in redirme
    await gen_tasks(session, url_list, payload_list, keyword)
  File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 39, in gen_tasks
    results = await asyncio.gather(*tasks)
  File "/home/kali/Bugbounty/OpenRedireX/openredirex.py", line 46, in getResponse
    async with session.get(r_url, allow_redirects=True, timeout=10) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 492, in _request
    req = self._request_class(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 366, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 88407996/articles?portalId=5212498&currentArticleId=10127762043&currentArticleLanguage=en&currentUrl=https://help.aware360.com/knowledge-base/setting-your&ssoLogin=false
